[Definition]
failregex = metasploitable sshd\[.*\]: Failed password for .* from <HOST>
ignoreregex =

[Init]
datepattern = {^LN-BEG}%%ExYear(?P<_sep>[-/.])%%m(?P=_sep)%%d[T ]%%H:%%M:%%S(?:[.,]%%f)?(?:\s*%%z)?
              ^%%b\s+%%d\s+%%H:%%M:%%S